webbds/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webbds.Models;
using System.Data.Entity;
using System.Net;
namespace webbds.Controllers
{
    public class HomeController : Controller
    {
        private BDS_TestEntities db = new BDS_TestEntities();
        public ActionResult Index()
        {
            var batDongSans = db.BatDongSans.Include(b => b.MoiGioi)
                                  .Where(b => b.TrangThai == true)
                                  .ToList();
            return View(batDongSans.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        // GET: BatDongSan/Details/5
        public ActionResult CT_BDS(int id)
        {
            var ct_bds = db.BatDongSans.FirstOrDefault(s => s.MaBatDongSan == id);
            Session["MaDuAn"] = ct_bds;
            return View(ct_bds);
        }
        public ActionResult MyProperties(int id)
        {
            var properties = db.BatDongSans.Where(b => b.MaDaiLy == id).ToList();
            return View(properties);
        }

        public ActionResult MoiGioiList()
        {
            var moiGiois = db.MoiGiois.ToList();
            return View(moiGiois);
        }

        public ActionResult MyProperties1(int id)
        {
            var properties = db.BatDongSans.Where(b => b.MaDaiLy == id).ToList();

            var moigioi = db.MoiGiois.FirstOrDefault(m => m.MaDaiLy == id);
            if (moigioi != null)
            {
                ViewBag.MoiGioiTen = moigioi.Ten;
            }

            return View(properties);
        }
    }
}

webbds/Controllers/LienHeNguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webbds.Models;
using System.Globalization;

namespace webbds.Controllers
{
    public class LienHeNguoiDungController : Controller
    {
        private BDS_TestEntities db = new BDS_TestEntities();

        // GET: LienHeNguoiDung
        public ActionResult Index()
        {
            var lienHeNguoiDungs = db.LienHeNguoiDungs.Include(l => l.BatDongSan).Include(l => l.NguoiDung).Include(l => l.TaiKhoan);
            return View(lienHeNguoiDungs.ToList());
        }

        // GET: LienHeNguoiDung/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LienHeNguoiDung lienHeNguoiDung = db.LienHeNguoiDungs.Find(id);
            if (lienHeNguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(lienHeNguoiDung);
        }

        // GET: LienHeNguoiDung/Create
        public ActionResult Create()
        {
            ViewBag.MaBatDongSan = new SelectList(db.BatDongSans, "MaBatDongSan", "TieuDe");
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "Ten");
            ViewBag.NguoiPhuTrach = new SelectList(db.TaiKhoans, "ID", "TaiKhoan1");
            return View();
        }

        // POST: LienHeNguoiDung/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NgayLienHe,SDT,GhiChu")] LienHeNguoiDung lienHeNguoiDung)
        {
            BatDongSan batdongsan = Session["MaDuAn"] as BatDongSan;
            NguoiDung nguoidung = Session["TaiKhoan"] as NguoiDung;

            int mabds = (int)batdongsan.MaBatDongSan;
            int manguoidung = (int)nguoidung.MaNguoiDung;
            //DateTime ngayLienHe = lienHeNguoiDung.NgayLienHe ?? DateTime.Now;
            DateTime? ngaylienhe = lienHeNguoiDung.NgayLienHe;
            if (ngaylienhe.HasValue && ngaylienhe.Value.Date > DateTime.Now.Date)
            {
                // Chuyển đổi ngày từ dd/MM/yyyy sang MM/dd/yyyy trước khi Parse
                string formattedDate = lienHeNguoiDung.NgayLienHe.Value.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture);
                // ParseExact thành ngày tháng năm trong format MM/dd/yyyy
                //ngaylienhe = DateTime.ParseExact(formattedDate, "MM/dd/yyyy", CultureInfo.InvariantCulture);
                ngaylienhe = DateTime.ParseExact(lienHeNguoiDung.NgayLienHe.Value.ToString("dd/MM/yyyy"), "dd/MM/yyyy", CultureInfo.InvariantCulture);
            }
            else
            {
                ngaylienhe = DateTime.Now;
            }
            string sdt = lienHeNguoiDung.SDT;
            string ghichu = lienHeNguoiDung.GhiChu;

            if (ModelState.IsValid)
            {
                //tạo một đối tượng mới LienHeNguoiDung và gán giá trị
                var lienhe = new LienHeNguoiDung
                {
                    MaBatDongSan = mabds,
                    MaNguoiDung = manguoidung,
                    NgayLienHe = ngaylienhe,
                    SDT = sdt,
                    GhiChu = ghichu
                };
                db.LienHeNguoiDungs.Add(lienhe);
                db.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            // Load các dữ liệu cần thiết để hiển thị lên View khi có lỗi
            ViewBag.MaBatDongSan = new SelectList(db.BatDongSans, "MaBatDongSan", "TieuDe", mabds);
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "Ten", manguoidung);
            ViewBag.NguoiPhuTrach = new SelectList(db.TaiKhoans, "ID", "TaiKhoan1", lienHeNguoiDung.NguoiPhuTrach);
            return View(lienHeNguoiDung);
        }

        // GET: LienHeNguoiDung/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LienHeNguoiDung lienHeNguoiDung = db.LienHeNguoiDungs.Find(id);
            if (lienHeNguoiDung == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaBatDongSan = new SelectList(db.BatDongSans, "MaBatDongSan", "TieuDe", lienHeNguoiDung.MaBatDongSan);
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "Ten", lienHeNguoiDung.MaNguoiDung);
            ViewBag.NguoiPhuTrach = new SelectList(db.TaiKhoans, "ID", "TaiKhoan1", lienHeNguoiDung.NguoiPhuTrach);
            return View(lienHeNguoiDung);
        }

        // POST: LienHeNguoiDung/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaLienHe,MaNguoiDung,MaBatDongSan,NgayLienHe,NguoiPhuTrach")] LienHeNguoiDung lienHeNguoiDung)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lienHeNguoiDung).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaBatDongSan = new SelectList(db.BatDongSans, "MaBatDongSan", "TieuDe", lienHeNguoiDung.MaBatDongSan);
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "Ten", lienHeNguoiDung.MaNguoiDung);
            ViewBag.NguoiPhuTrach = new SelectList(db.TaiKhoans, "ID", "TaiKhoan1", lienHeNguoiDung.NguoiPhuTrach);
            return View(lienHeNguoiDung);
        }

        // GET: LienHeNguoiDung/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LienHeNguoiDung lienHeNguoiDung = db.LienHeNguoiDungs.Find(id);
            if (lienHeNguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(lienHeNguoiDung);
        }

        // POST: LienHeNguoiDung/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LienHeNguoiDung lienHeNguoiDung = db.LienHeNguoiDungs.Find(id);
            db.LienHeNguoiDungs.Remove(lienHeNguoiDung);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webbds/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webbds.Models;

namespace webbds.Controllers
{
    public class SearchController : Controller
    {
        private BDS_TestEntities db = new BDS_TestEntities();
        // GET: Search
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SearchProject(string keyword)
        {
            var projects = db.BatDongSans
                            .Where(p => p.TieuDe.Contains(keyword) && p.TrangThai==true)
                            .ToList();

            if (projects.Count == 0)
            {
                // Xử lý khi không tìm thấy dự án
                ViewBag.Message = "Không tìm thấy dự án phù hợp";
                return View("NotFound"); // Tạo view "NotFound" để hiển thị thông báo không tìm thấy dự án
            }
            else
            {
                return View(projects);
            }
        }
    }
}

webbds/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

webbds/Views/Home/CT_BDS.cshtml
@model webbds.Models.BatDongSan

@{
    ViewBag.Title = "CT_BDS";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
}

<div class="container">


    <div class="container">
        <div class="bg-light p-5 text-center" style="background-image: url('https://media.vneconomy.vn/w800/images/upload/2022/11/16/56c99f14-2861-4dc2-ae06-3c04c8b22a63.jpg');">
            <h2 style="color:aliceblue !important">An tâm chọn, An tâm mua</h2>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-6">
                        <form action="@Url.Action("SearchProject", "Search")" method="get">
                            <div class="input-group my-3">
                                <input type="text" name="keyword" class="form-control" placeholder="Nhập từ khóa tìm kiếm">
                                <button class="btn btn-light" type="submit">
                                    <img style="width: 24px; height: 24px" src="~/Content/Images/search-interface-symbol.png" />
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class=" bg-gray bg-light shadow-lg pt-3 rounded-lg">
        <div class="row ">
            <div class="col-sm-5">
                <img style="width: 98%" src="@Url.Content(Model.Anh)" />
            </div>
            <div class="col-sm-7">
                <!--ten du an-->
                <div class="pt-3">
                    <h3 style="font-weight:600">
                        @Html.DisplayFor(model => model.TieuDe)
                    </h3>
                </div>
                <!--vị trí-->
                <div class="pt-3">
                    <h4>
                        @Html.DisplayFor(model => model.ViTri)
                    </h4>
                </div>
                <!--giá-->
                <h5 style="color: red" class="pt-3">Giá từ: @((Model.Gia ?? 0).ToString("0.##")) VNĐ</h5>
                <!--Thông tin dự án-->

                <div class="row pt-3">
                    <div class="col-sm-6">

                        <div class="row">
                            <div class="col-sm-4 text-muted ">

                                <p>Tổng diện tích:</p>
                                <p>Tiện nghi:</p>
                                <p>Pháp lý:</p>


                            </div>
                            <div class="col-sm-8">

                                <p>@Html.DisplayFor(model => model.DienTich) m&sup2</p>
                                <p>@Html.DisplayFor(model => model.TienNghi)</p>
                                <p>@Html.DisplayFor(model => model.PhapLy)</p>


                            </div>
                        </div>


                    </div>
                    <div class="col-sm-6">

                        <div class="row">
                            <div class="col-sm-5 text-muted">
                                <p>Chủ dự án:</p>
                                <p>Email:</p>
                                <p>Liên hệ:</p>
                                <p>Địa chỉ:</p>
                            </div>
                            <div class="col-sm-7">
                                <p>@Html.DisplayFor(model => model.MoiGioi.Ten)</p>
                                <p>@Html.DisplayFor(model => model.MoiGioi.Email)</p>
                                <p>@Html.DisplayFor(model => model.MoiGioi.DienThoai)</p>
                                <p>@Html.DisplayFor(model => model.MoiGioi.DiaChi)</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-sm-5 pt-3 d-flex justify-content-lg-around" style="height:55px">
                <div>
                    @Html.ActionLink("Đặt lịch", "Create", "LienHeNguoiDung", new { id = Model.MaBatDongSan }, new { @class = "btn btn-primary" })
                </div>
                <button type="button" class="btn btn-success">Yêu Thích</button>
                <button type="button" class="btn btn-danger">
                    <a style="color:white; text-decoration:none" href="mailto:@Model.MoiGioi.Email">Liên Hệ Nhà Môi Giới</a>
                </button>
            </div>
            <div class="col-sm-7">
                <!--mô tả-->
                <div class="pt-3">
                    <h4>Mô tả:</h4>
                    <p>@Html.DisplayFor(model => model.MoTa)</p>
                </div>
            </div>
        </div>

    </div>
    <!--gg map-->
    <div class="pt-3">
        <iframe src="@Html.DisplayFor(model => model.urlmap)" width="100%" height="350"></iframe>
    </div>
</div>

webbds/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = " ~/Views/Shared/NguoiDung_Layout.cshtml";
}


<div class="container mt-5">
    <h2>Chào mừng đến với Trang Web Bất động sản của chúng tôi</h2>
    <hr />

    <p>
        Xin chào tất cả bạn đang quan tâm và tìm hiểu về thế giới bất động sản! Trang web này được tạo ra như một dự án báo cáo cuối kì của sinh viên, với mục đích tạo một môi trường thực tế để thực hành và trải nghiệm quá trình phát triển ứng dụng web.
    </p>

    <h3>Vì sao chọn trang web Bất động sản của chúng tôi?</h3>
    <p>
        Trang web Bất động sản của chúng tôi không chỉ đơn thuần là một dự án học tập, mà còn là một nền tảng thú vị để bạn khám phá và áp dụng kiến thức về quản lý, tạo và quản lý danh sách các bất động sản.
    </p>

    <h3>Tính năng nổi bật</h3>
    <ul>
        <li>Tạo mới, chỉnh sửa và xóa các bất động sản.</li>
        <li>Tương tác với người dùng khác qua chức năng bình luận và đánh giá.</li>
        <li>Xem danh sách các bất động sản nổi bật và danh sách của riêng bạn.</li>
        <li>Nhận thông báo về các cập nhật mới từ các bất động sản bạn quan tâm.</li>
    </ul>

    <h3>Phản hồi và Góp ý</h3>
    <p>
        Chúng tôi luôn hoan nghênh mọi ý kiến đóng góp và phản hồi từ bạn. Nếu bạn có bất kỳ ý tưởng nào để cải thiện trang web hoặc muốn chia sẻ trải nghiệm của mình, vui lòng liên hệ với chúng tôi qua trang Liên hệ.
    </p>

    <p>
        Cảm ơn bạn đã ghé thăm và ủng hộ trang web Bất động sản của chúng tôi!
    </p>
</div>

webbds/Views/Home/Index.cshtml
@model IEnumerable<webbds.Models.BatDongSan>
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main>
    <div class="container">
        <div class="bg-light p-5 text-center" style="background-image: url('https://media.vneconomy.vn/w800/images/upload/2022/11/16/56c99f14-2861-4dc2-ae06-3c04c8b22a63.jpg'); background-size: cover; background-position: center;">
            <h2 style="color: #fff !important">An tâm chọn, An tâm mua</h2>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-6">
                        <form action="@Url.Action("SearchProject", "Search")" method="get">
                            <div class="input-group my-3">
                                <input type="text" name="keyword" class="form-control" placeholder="Nhập từ khóa tìm kiếm">
                                <button class="btn btn-light" type="submit">
                                    <img style="width: 24px; height: 24px" src="~/Content/Images/search-interface-symbol.png" />
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container my-5">
        <h2 class="text-center">Dự án nổi bật</h2>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4 col-sm-6 mb-4">
                    <div class="card">
                        <a style="text-decoration: none !important; color: black;" href="@Url.Action("CT_BDS", "Home", new { id = item.MaBatDongSan })">
                            <img class="card-img-top" src="@Url.Content(item.Anh)" alt="Hình ảnh dự án" style="height: 200px;">
                            <div class="card-body">
                                <h5 class="card-title">@item.TieuDe</h5>
                                <p class="card-text">@item.Gia</p>
                            </div>
                        </a>
                    </div>
                </div>
            }
        </div>
    </div>

    <div class="container p-2">
        <img src="https://cdn.mogi.vn/banner/2023/6_a85230e0-b73a-4e11-acb1-d4788b5d85a4.png" class="mx-auto d-block" style="width: 100%; max-height: 200px;" />
    </div>
</main>

webbds/Views/Home/MyProperties1.cshtml
@model IEnumerable<webbds.Models.BatDongSan>

@{
    ViewBag.Title = "MyProperties1";
    Layout = "~/Views/Shared/NguoiDung_Layout.cshtml";
}

<div class="container">
    <h2>Các bất động sản của @ViewBag.MoiGioiTen</h2>
    <hr />
    @foreach (var property in Model)
    {
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">@property.TieuDe</h5>
                <p class="card-text">@property.MoTa</p>
                <a href="@Url.Action("CT_BDS", "Home", new { id = property.MaBatDongSan })" class="btn btn-primary">Xem chi tiết</a>
            </div>
        </div>
    }
</div>