webbds/Controllers/BatDongSanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webbds.Models;
using System.IO;

namespace webbds.Controllers
{
    public class BatDongSanController : Controller
    {
        private BDS_TestEntities db = new BDS_TestEntities();

        // GET: BatDongSan
        public ActionResult Index()
        {
            var batDongSans = db.BatDongSans.Include(b => b.MoiGioi);
            return View(batDongSans.ToList());
        }

        // GET: BatDongSan/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BatDongSan batDongSan = db.BatDongSans.Find(id);
            if (batDongSan == null)
            {
                return HttpNotFound();
            }
            return View(batDongSan);
        }

        // GET: BatDongSan/Create
        public ActionResult Create()
        {
            ViewBag.MaDaiLy = new SelectList(db.MoiGiois, "MaDaiLy", "Ten");
            return View();
        }

        // POST: BatDongSan/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaBatDongSan,TieuDe,MoTa,Gia,DienTich,ViTri,Anh,TienNghi,ThongTinLienHe,NgayTao,NgaySua,MaDaiLy,urlmap")] BatDongSan batDongSan, HttpPostedFileBase Anh)
        {
            MoiGioi moigioi = Session["MoiGioi"] as MoiGioi;
            int MaMG = (int)moigioi.MaDaiLy;
            batDongSan.TrangThai = false;
            if (ModelState.IsValid)
            {
                    
                if (Anh != null && Anh.ContentLength > 0)
                {
                    // Lưu hình ảnh vào thư mục ~/Content/Images
                    var filename = Path.GetFileName(Anh.FileName);
                    var serverPath = Server.MapPath("~/Content/Images");
                    var path = Path.Combine(serverPath, filename);
                    Anh.SaveAs(path);

                    // Lưu đường dẫn của hình ảnh vào trường Anh của đối tượng BatDongSan
                    batDongSan.Anh = "~/Content/Images/" + filename;
                }
                batDongSan.MaDaiLy = MaMG;
                db.BatDongSans.Add(batDongSan);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            ViewBag.MaDaiLy = new SelectList(db.MoiGiois, "MaDaiLy", "Ten", batDongSan.MaDaiLy);
            return RedirectToAction("Index");
        }

        // GET: BatDongSan/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BatDongSan batDongSan = db.BatDongSans.Find(id);
            if (batDongSan == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDaiLy = new SelectList(db.MoiGiois, "MaDaiLy", "Ten", batDongSan.MaDaiLy);
            return View(batDongSan);
        }

        // POST: BatDongSan/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaBatDongSan,TieuDe,MoTa,Gia,DienTich,ViTri,Anh,TienNghi,ThongTinLienHe,NgayTao,NgaySua,MaDaiLy,TrangThai,urlmap")] BatDongSan batDongSan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(batDongSan).State = (System.Data.Entity.EntityState)System.Data.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaDaiLy = new SelectList(db.MoiGiois, "MaDaiLy", "Ten", batDongSan.MaDaiLy);
            return View(batDongSan);
        }

        // GET: BatDongSan/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BatDongSan batDongSan = db.BatDongSans.Find(id);
            if (batDongSan == null)
            {
                return HttpNotFound();
            }
            return View(batDongSan);
        }

        // POST: BatDongSan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BatDongSan batDongSan = db.BatDongSans.Find(id);
            db.BatDongSans.Remove(batDongSan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public ActionResult MyProperties()
        {
            // Lấy thông tin người dùng đang đăng nhập từ session
            MoiGioi moigioi = Session["MoiGioi"] as MoiGioi;
            if (moigioi == null)
            {
                // Nếu người dùng không đăng nhập, chuyển hướng hoặc xử lý tùy ý
                return RedirectToAction("Create", "MoiGioi"); // Ví dụ: chuyển hướng đến trang đăng nhập
            }

            // Lấy danh sách bất động sản của người dùng từ cơ sở dữ liệu
            var properties = db.BatDongSans.Where(b => b.MaDaiLy == moigioi.MaDaiLy).ToList();

            return View(properties);
        }

        public ActionResult AllProperties()
        {
            var properties = db.BatDongSans.Where(prop => prop.TrangThai == true).ToList();
            return View(properties);
        }



    }
}

webbds/Controllers/NhanXetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webbds.Models;

namespace webbds.Controllers
{
    public class NhanXetController : Controller
    {
        private BDS_TestEntities db = new BDS_TestEntities();

        // GET: NhanXet
        public ActionResult Index()
        {
            var nhanXets = db.NhanXets.Include(n => n.BatDongSan).Include(n => n.NguoiDung);
            return View(nhanXets.ToList());
        }

        // GET: NhanXet/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanXet nhanXet = db.NhanXets.Find(id);
            if (nhanXet == null)
            {
                return HttpNotFound();
            }
            return View(nhanXet);
        }

        // GET: NhanXet/Create
        public ActionResult Create()
        {
            // Khởi tạo đối tượng view model
            var viewModel = new NhanXetViewModel();
            viewModel.Comments = db.NhanXets.ToList();
            viewModel.NewComment = new NhanXet();

            // Lấy thông tin người dùng hiện tại từ Session
            var currentUser = Session["TaiKhoan"] as NguoiDung;

            // Nếu có người dùng đăng nhập, thiết lập MaNguoiDung cho NewComment
            if (currentUser != null)
            {
                viewModel.NewComment.MaNguoiDung = currentUser.MaNguoiDung;
            }

            // Trả về view với view model đã thiết lập
            return View(viewModel);

        }

        // POST: NhanXet/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NhanXetViewModel nhanXetViewModel)
        {
            if (ModelState.IsValid)
            {
                var currentUser = Session["TaiKhoan"] as NguoiDung;

                if (currentUser != null && nhanXetViewModel.NewComment != null)
                {
                    int manguoidung = currentUser.MaNguoiDung;

                    // Tạo một đối tượng NhanXet mới và gán các thuộc tính
                    NhanXet newComment = new NhanXet
                    {
                        MaNguoiDung = manguoidung,
                        BinhLuan = nhanXetViewModel.NewComment.BinhLuan
                    };

                    // Thêm đối tượng NhanXet mới vào cơ sở dữ liệu và lưu thay đổi
                    db.NhanXets.Add(newComment);
                    db.SaveChanges();
                }

                // Redirect về trang hiện tại để làm mới phần hiển thị bình luận
                return RedirectToAction("Create");
            }

            // Nếu ModelState không hợp lệ, load lại danh sách bình luận và hiển thị lại trang
            nhanXetViewModel.Comments = db.NhanXets.ToList();
            return View(nhanXetViewModel);
        }

        // GET: NhanXet/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanXet nhanXet = db.NhanXets.Find(id);
            if (nhanXet == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaBatDongSan = new SelectList(db.BatDongSans, "MaBatDongSan", "TieuDe", nhanXet.MaBatDongSan);
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "Ten", nhanXet.MaNguoiDung);
            return View(nhanXet);
        }

        // POST: NhanXet/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNhanXet,MaBatDongSan,MaNguoiDung,DanhGia,BinhLuan")] NhanXet nhanXet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhanXet).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaBatDongSan = new SelectList(db.BatDongSans, "MaBatDongSan", "TieuDe", nhanXet.MaBatDongSan);
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "Ten", nhanXet.MaNguoiDung);
            return View(nhanXet);
        }

        // GET: NhanXet/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanXet nhanXet = db.NhanXets.Find(id);
            if (nhanXet == null)
            {
                return HttpNotFound();
            }
            return View(nhanXet);
        }

        // POST: NhanXet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NhanXet nhanXet = db.NhanXets.Find(id);
            db.NhanXets.Remove(nhanXet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webbds/Views/Shared/MoiGioi_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap">
    <style>
        .custom-font {
            font-family: 'Source Sans Pro', sans-serif;
        }
    </style>
</head>
<body class="custom-font" style=" background-color: #EAE0DA; padding: 0; margin: 0">
    <nav style="background-color: #F7F5EB !important" class="navbar navbar-expand-sm bg-light navbar-light">
        <div class="container">
            @Html.ActionLink("Công Ty Bất Động Sản", "Index", "MoiGioi", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="d-flex">
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                     
                        <li>@Html.ActionLink("Giới thiệu", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Dự án", "MyProperties", "BatDongSan", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Đăng tin", "Create", "BatDongSan", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>
                            @Html.ActionLink("Đăng xuất", "Index", "Home", new { area = "" }, new { @class = "btn btn-outline-dark nav-link" })
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>

    <footer style="background-color: #F7F5EB !important" class="bg-light">
        <div class="mt-5 p-4">
            <div class="row">
                <div class="col-sm-4">
                    <h6>Column 1</h6>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
                    <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.638858498883!2d106.66488107817302!3d10.76229123210971!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752ee40d3878d1%3A0xccc015efaaefb3a4!2zMjc4IEhvw6AgSOG6o28sIFBoxrDhu51uZyA0LCBRdeG6rW4gMTAsIFRow6BuaCBwaOG7kSBI4buTIENow60gTWluaCwgVmnhu4d0IE5hbQ!5e0!3m2!1svi!2sus!4v1688471092563!5m2!1svi!2sus"
                            width="400" height="150" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
                <div class="col-sm-2">
                    <h6>Bất động sản TPHCM</h6>
                    <div style="font-size:14px">
                        <p>Mua bán nhà đất TPHCM</p>
                        <p>Bán nhà quận 7</p>
                        <p>Bán căn hộ quận 7</p>
                        <p>Bán đất quận 9</p>
                        <p>Bán nhà quận 10</p>
                        <p>Bán nhà quận 8</p>
                    </div>
                </div>
                <div class="col-sm-2">
                    <h6>Bất động sản Hà Nội</h6>
                    <div style="font-size:14px">
                        <p>Bán đất Hà Nội</p>
                        <p>Bán nhà Hà Nội</p>
                        <p>Cho thuê nhà Hà Nội</p>
                        <p>Chung cư Hà Nội</p>
                        <p>Nhà đất Hà Nội</p>
                        <p>Phòng trọ Hà Nội</p>
                    </div>
                </div>
                <div class="col-sm-2">
                    <h6>Mua bán bất động sản</h6>
                    <div style="font-size:14px">
                        <p>Bán đất Bình Dương</p>
                        <p>Bất động sản Đà Nẵng</p>
                        <p>Căn hộ chung cư</p>
                        <p>Mua bán nhà đất</p>
                        <p> Nhà đất Hải Phòng</p>
                        <p>Sang quán cafe</p>
                    </div>

                </div>
                <div class="col-sm-2">
                    <h6>Cho thuê nhà đất</h6>
                    <div style="font-size:14px">
                        <p>Cho thuê căn hộ</p>
                        <p>Cho thuê mặt bằng</p>
                        <p>Cho thuê nhà nguyên căn</p>
                        <p>Cho thuê nhà xưởng</p>
                        <p>Cho thuê phòng trọ</p>
                        <p>Cho thuê văn phòng</p>
                    </div>

                </div>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

webbds/Views/Shared/NguoiDung_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap">
    <style>
        .custom-font {
            font-family: 'Source Sans Pro', sans-serif;
        }
    </style>
</head>
<body class="custom-font" style=" background-color: #EAE0DA; padding: 0; margin: 0">
    <nav style="background-color: #F7F5EB !important" class="navbar navbar-expand-sm bg-light navbar-light">
        <div class="container">
            @Html.ActionLink("Công Ty Bất Động Sản", "Index", "NguoiDung", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="d-flex">
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>@Html.ActionLink("Hỏi đáp", "Create", "NhanXet", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Môi giới", "Details", "MoiGioi", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Dự án", "AllProperties", "BatDongSan", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Giới thiệu", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>
                            @Html.ActionLink("Đăng xuất", "Index", "Home", new { area = "" }, new { @class = "btn btn-outline-dark nav-link" })
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    <footer style="background-color: #F7F5EB !important" class="bg-light">
        <div class="mt-5 p-4">
            <div class="row">
                <div class="col-sm-4">
                    <h6>Nhóm 8</h6>
                    <p>Đồ án công nghệ phần mềm</p>
                    <p>Tham khảo từ Mogi.vn</p>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.638858498883!2d106.66488107817302!3d10.76229123210971!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752ee40d3878d1%3A0xccc015efaaefb3a4!2zMjc4IEhvw6AgSOG6o28sIFBoxrDhu51uZyA0LCBRdeG6rW4gMTAsIFRow6BuaCBwaOG7kSBI4buTIENow60gTWluaCwgVmnhu4d0IE5hbQ!5e0!3m2!1svi!2sus!4v1688471092563!5m2!1svi!2sus"
                            width="400" height="150" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
                <div class="col-sm-2">
                    <h6>Bất động sản TPHCM</h6>
                    <div style="font-size:14px">
                        <p>Mua bán nhà đất TPHCM</p>
                        <p>Bán nhà quận 7</p>
                        <p>Bán căn hộ quận 7</p>
                        <p>Bán đất quận 9</p>
                        <p>Bán nhà quận 10</p>
                        <p>Bán nhà quận 8</p>
                    </div>
                </div>
                <div class="col-sm-2">
                    <h6>Bất động sản Hà Nội</h6>
                    <div style="font-size:14px">
                        <p>Bán đất Hà Nội</p>
                        <p>Bán nhà Hà Nội</p>
                        <p>Cho thuê nhà Hà Nội</p>
                        <p>Chung cư Hà Nội</p>
                        <p>Nhà đất Hà Nội</p>
                        <p>Phòng trọ Hà Nội</p>
                    </div>
                </div>
                <div class="col-sm-2">
                    <h6>Mua bán bất động sản</h6>
                    <div style="font-size:14px">
                        <p>Bán đất Bình Dương</p>
                        <p>Bất động sản Đà Nẵng</p>
                        <p>Căn hộ chung cư</p>
                        <p>Mua bán nhà đất</p>
                        <p> Nhà đất Hải Phòng</p>
                        <p>Sang quán cafe</p>
                    </div>

                </div>
                <div class="col-sm-2">
                    <h6>Cho thuê nhà đất</h6>
                    <div style="font-size:14px">
                        <p>Cho thuê căn hộ</p>
                        <p>Cho thuê mặt bằng</p>
                        <p>Cho thuê nhà nguyên căn</p>
                        <p>Cho thuê nhà xưởng</p>
                        <p>Cho thuê phòng trọ</p>
                        <p>Cho thuê văn phòng</p>
                    </div>

                </div>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

webbds/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap">
    <style>
        .custom-font {
            font-family: 'Source Sans Pro', sans-serif;
        }
    </style>
</head>
<body class="custom-font" style=" background-color: #EAE0DA; padding: 0; margin: 0">
    <nav style="background-color: #F7F5EB !important" class="navbar navbar-expand-sm bg-light navbar-light">
        <div class="container">
            @Html.ActionLink("Công Ty Bất Động Sản", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="d-flex">
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>@Html.ActionLink("Hỏi đáp", "Create", "NhanXet", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Môi giới", "Create", "MoiGioi", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Dự án", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Đăng nhập", "Create", "NguoiDung", new { area = "" }, new { @class = "nav-link" })</li>
                        <li><button type="button" class="btn btn-outline-dark">Đăng tin</button></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <div  class="container body-content">
        @RenderBody()
    </div>
    <footer style="background-color: #F7F5EB !important" class="bg-light">
        <div class="mt-5 p-4">
            <div class="row">
                <div class="col-sm-4">
                    <h6>Nhóm 8</h6>
                    <p>Đồ án công nghệ phần mềm</p>
                    <p>Tham khảo từ Mogi.vn</p>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.638858498883!2d106.66488107817302!3d10.76229123210971!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752ee40d3878d1%3A0xccc015efaaefb3a4!2zMjc4IEhvw6AgSOG6o28sIFBoxrDhu51uZyA0LCBRdeG6rW4gMTAsIFRow6BuaCBwaOG7kSBI4buTIENow60gTWluaCwgVmnhu4d0IE5hbQ!5e0!3m2!1svi!2sus!4v1688471092563!5m2!1svi!2sus"
                            width="400" height="150" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
                <div class="col-sm-2">
                    <h6>Bất động sản TPHCM</h6>
                    <div style="font-size:14px">
                        <p>Mua bán nhà đất TPHCM</p>
                        <p>Bán nhà quận 7</p>
                        <p>Bán căn hộ quận 7</p>
                        <p>Bán đất quận 9</p>
                        <p>Bán nhà quận 10</p>
                        <p>Bán nhà quận 8</p>
                    </div>
                </div>
                <div class="col-sm-2">
                    <h6>Bất động sản Hà Nội</h6>
                    <div style="font-size:14px">
                        <p>Bán đất Hà Nội</p>
                        <p>Bán nhà Hà Nội</p>
                        <p>Cho thuê nhà Hà Nội</p>
                        <p>Chung cư Hà Nội</p>
                        <p>Nhà đất Hà Nội</p>
                        <p>Phòng trọ Hà Nội</p>
                    </div>
                </div>
                <div class="col-sm-2">
                    <h6>Mua bán bất động sản</h6>
                    <div style="font-size:14px">
                        <p>Bán đất Bình Dương</p>
                        <p>Bất động sản Đà Nẵng</p>
                        <p>Căn hộ chung cư</p>
                        <p>Mua bán nhà đất</p>
                        <p> Nhà đất Hải Phòng</p>
                        <p>Sang quán cafe</p>
                    </div>

                </div>
                <div class="col-sm-2">
                    <h6>Cho thuê nhà đất</h6>
                    <div style="font-size:14px">
                        <p>Cho thuê căn hộ</p>
                        <p>Cho thuê mặt bằng</p>
                        <p>Cho thuê nhà nguyên căn</p>
                        <p>Cho thuê nhà xưởng</p>
                        <p>Cho thuê phòng trọ</p>
                        <p>Cho thuê văn phòng</p>
                    </div>

                </div>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>